<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>BinTracker</AssemblyName>
    <RootNamespace>BinTracker.WinForms</RootNamespace>
    <Product>BinTracker</Product>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BinTracker.Core\BinTracker.Core.csproj" />
    <ProjectReference Include="..\BinTracker.Data\BinTracker.Data.csproj" />
    <ProjectReference Include="..\BinTracker.Services\BinTracker.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>
</Project>
